<?php

/**
 * MIT License
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace SprykerEco\Shared\AkeneoPimMiddlewareConnector;

interface AkeneoPimMiddlewareConnectorConstants
{
    public const LOCALE_MAP_FILE_PATH = 'AKENEOPIMMIDDLEWARECONNECTOR:LOCALE_MAP_FILE_PATH';
    public const ATTRIBUTE_MAP_FILE_PATH = 'AKENEOPIMMIDDLEWARECONNECTOR:ATTRIBUTE_MAP_FILE_PATH';
    public const SUPER_ATTRIBUTE_MAP_FILE_PATH = 'AKENEOPIMMIDDLEWARECONNECTOR:SUPER_ATTRIBUTE_MAP_FILE_PATH';
    public const FK_CATEGORY_TEMPLATE = 'AKENEOPIMMIDDLEWARECONNECTOR:FK_CATEGORY_TEMPLATE';
    public const TAX_SET = 'AKENEOPIMMIDDLEWARECONNECTOR:TAX_SET';
    public const LOCALES_FOR_IMPORT = 'AKENEOPIMMIDDLEWARECONNECTOR:LOCALES_FOR_IMPORT';
    public const LOCALES_TO_PRICE_MAP = 'AKENEOPIMMIDDLEWARECONNECTOR:LOCALES_TO_PRICE_MAP';
    public const ACTIVE_STORES_FOR_PRODUCTS = 'AKENEOPIMMIDDLEWARECONNECTOR:ACTIVE_STORES_FOR_PRODUCTS';
    public const SKU_VALUE_FILE_PATH = 'AKENEOPIMMIDDLEWARECONNECTOR:SKU_VALUE_FILE_PATH';
}
