<?php

/**
 * MIT License
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace SprykerEco\Shared\AkeneoPimMiddlewareConnector;

interface AkeneoPimMiddlewareConnectorConstants
{
    const LOCALE_MAP_FILE_PATH = 'AKENEOPIMMIDDLEWARECONNECTOR:LOCALE_MAP_FILE_PATH';
    const ATTRIBUTE_MAP_FILE_PATH = 'AKENEOPIMMIDDLEWARECONNECTOR:ATTRIBUTE_MAP_FILE_PATH';
    const SUPER_ATTRIBUTE_MAP_FILE_PATH = 'AKENEOPIMMIDDLEWARECONNECTOR:SUPER_ATTRIBUTE_MAP_FILE_PATH';
    const DEFAULT_FK_CATEGORY_TEMPLATE = 'AKENEOPIMMIDDLEWARECONNECTOR:DEFAULT_FK_CATEGORY_TEMPLATE';
    const DEFAULT_TAX_SET = 'AKENEOPIMMIDDLEWARECONNECTOR:DEFAULT_TAX_SET';
    const LOCALES_FOR_IMPORT = 'AKENEOPIMMIDDLEWARECONNECTOR:LOCALES_FOR_IMPORT';
    const DEFAULT_STORES_FOR_PRODUCTS = 'AKENEOPIMMIDDLEWARECONNECTOR:DEFAULT_STORES_FOR_PRODUCTS';
}
